-- 1번.
SELECT 
    DEPARTMENT_NAME AS "학과 명", 
    CATEGORY AS "계열"
FROM TB_DEPARTMENT;

-- 2번.
SELECT 
    DEPARTMENT_NAME || '과의 정원은 ' || CAPACITY || '명 입니다.' AS "학과별 정원"
FROM TB_DEPARTMENT;--왜 OR표시를 했는가?

-- 3번.
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE DEPARTMENT_NO = '001' AND ABSENCE_YN = 'Y' AND STUDENT_SSN LIKE '_______2%';

-- 4번.
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE STUDENT_NO IN ('A513079', 'A513090', 'A513091' , 'A513110', 'A513119')
ORDER BY STUDENT_NAME DESC;--WHERE과 ORDER 출력차이

-- 5번.
SELECT 
    DEPARTMENT_NAME, 
    CATEGORY
FROM TB_DEPARTMENT
WHERE CAPACITY BETWEEN 20 AND 30;

-- 6번.
SELECT PROFESSOR_NAME
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO IS NULL;--WHERE DEPARTMENT_NO NOT IN (SELECT DEPARTMENT_NO
                               FROM TB_DEPARTMENT);------------>(홍석님꺼) 뭔소리인가


-- 7번.
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE DEPARTMENT_NO IS NULL;

-- 8번.
SELECT CLASS_NO
FROM TB_CLASS
WHERE PREATTENDING_CLASS_NO IS NOT NULL;

-- 9번.
SELECT DISTINCT CATEGORY
FROM TB_DEPARTMENT
ORDER BY CATEGORY;--중복된 CATEGORY(과)가 있어서 DISTINCY써준거?

-- 10번.
SELECT 
    STUDENT_NO, 
    STUDENT_NAME, 
    STUDENT_SSN
FROM TB_STUDENT
WHERE ENTRANCE_DATE LIKE '02%' AND STUDENT_ADDRESS LIKE '%전주%' AND ABSENCE_YN LIKE 'N';
SELECT DEPARTMENT_NAME='002',STUDENT_NO AS 학번, STUDENT_NAME
